# Generated by Django 5.0.6 on 2024-06-29 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("short_name", models.CharField(max_length=5)),
            ],
            options={
                "verbose_name_plural": "0. Categorys",
            },
        ),
        migrations.CreateModel(
            name="Units",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("short_name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "2. Units",
            },
        ),
        migrations.CreateModel(
            name="Vendors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("photo", models.ImageField(blank=True, upload_to="photo_vendor/")),
                ("adress", models.TextField(max_length=50)),
                ("mobile", models.CharField(max_length=15)),
                ("status", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "1. Vendors",
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("detail", models.CharField(max_length=50)),
                ("photo", models.ImageField(blank=True, upload_to="imgproduct/")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MonStock.categorys",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MonStock.units"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "3. Products",
            },
        ),
        migrations.CreateModel(
            name="Purchases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.FloatField(default=0)),
                ("price", models.FloatField(default=0)),
                ("total_amount", models.FloatField(default=0, editable=False)),
                ("pur_date", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MonStock.products",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MonStock.vendors",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "4. Purchases",
            },
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.FloatField()),
                ("price", models.FloatField()),
                ("total_amount", models.FloatField(editable=False)),
                ("sale_date", models.DateTimeField(auto_now_add=True)),
                ("customer_name", models.CharField(blank=True, max_length=100)),
                ("customer_adresse", models.TextField(blank=True, max_length=100)),
                ("customer_mobile", models.CharField(blank=True, max_length=15)),
                ("customer_email", models.EmailField(blank=True, max_length=50)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MonStock.products",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "5. Sales",
            },
        ),
        migrations.CreateModel(
            name="Inventorys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pur_qty", models.FloatField(default=0, null=True)),
                ("sale_qty", models.FloatField(default=0, null=True)),
                ("total_bal_qty", models.FloatField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MonStock.products",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MonStock.purchases",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MonStock.sales",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "6. Inventorys",
            },
        ),
    ]
